baseURL = 'https://bitmonkay.github.io/3monkeys-podcast/'
languageCode = 'en-us'
title = '3monkeys Podcast'
theme = 'anatole'

[params]

title = "三个程序员"
author = "3monkeys"
description = "聊聊职业发展那些事"
profilePicture = "images/3monkeys.jpeg"

[params.podcastAuthor]
name = "3monkeys"
email = "wh_linux@126.com"

[params.podcast]
description = "3 code monkeys talk about career"
tagline = "3monkeys - Career"
download_url = "https://bitmonkay.github.io/episodes/"
itunes_url = "https://podcasts.apple.com/us/podcast/foodie-flashback/TODO"
itunes_id = "TODO"


[outputFormats]
[outputFormats.aacfeed]
MediaType = "application/rss+xml"
BaseName = "index"
path = "/feed/aac"
IsHTML = false
IsPlainText = true
noUgly = true
Rel = "alternate"
[outputFormats.mp3feed]
MediaType = "application/rss+xml"
BaseName = "index"
path = "/feed/mp3"
IsHTML = false
IsPlainText = true
noUgly = true
Rel = "alternate"

[outputs]
home = ["HTML", "AMP", "RSS", "aacfeed", "mp3feed"]

[menu]
  [[menu.main]]
  name = "Episodes"
  identifier = "episodes"
  weight = 100
  url = "/episodes/"