baseURL = 'https://bitmonkay.github.io/3monkeys-podcast/'
languageCode = 'en-us'
title = '3monkeys Podcast'
theme = 'anatole'

[params]
[params.author]
name = "3monkeys"
email = "wh_linux@126.com"
twitter = "@grayking"

mainSections = ["blog", "episodes"] # see https://gohugo.io/functions/where/#mainsections

[params.podcast]
description = "3 code monkeys talk about career"
tagline = "3monkeys - Career"
download_url = "https://cdn.linuxzen.com/episodes/"
cdn_url = "https://cdn.linuxzen.com/"
itunes_url = "https://podcasts.apple.com/us/podcast/foodie-flashback/id1504783815"
itunes_id = "id1504783815"

[outputFormats]
[outputFormats.aacfeed]
MediaType = "application/rss+xml"
BaseName = "index"
path = "/feed/aac"
IsHTML = false
IsPlainText = true
noUgly = true
Rel = "alternate"
[outputFormats.mp3feed]
MediaType = "application/rss+xml"
BaseName = "index"
path = "/feed/mp3"
IsHTML = false
IsPlainText = true
noUgly = true
Rel = "alternate"

[outputs]
home = ["HTML", "AMP", "RSS", "aacfeed", "mp3feed"]
